/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moneyexchange;

import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class MenuUtama extends javax.swing.JFrame {
    
    
    int userIDR = 150000;
    int userUSD = 911;
    int userEUR = 102;
    int userGBP = 140;
    int perubahanNilai;
    boolean ulangKalkulasi = true;
    boolean kalkulasiPositif;
    int inputNominal;
    int[] nilaiTukar = {15000, 16000, 18000};
    
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }
    
    public void resetDataDeposit() {
        IDRAkunText.setText(String.valueOf(userIDR));
        USDAkunText.setText(String.valueOf(userUSD));
        EURAkunText.setText(String.valueOf(userEUR));
        GBPAkunText.setText(String.valueOf(userGBP));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        nilaiTukarUSD = new javax.swing.JLabel();
        nilaiTukarEUR = new javax.swing.JLabel();
        nilaiTukarGBP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDRAkunText = new javax.swing.JLabel();
        USDAkunText = new javax.swing.JLabel();
        EURAkunText = new javax.swing.JLabel();
        GBPAkunText = new javax.swing.JLabel();
        JualUSDButton = new javax.swing.JButton();
        BeliUSDButton = new javax.swing.JButton();
        JualEURButton = new javax.swing.JButton();
        BeliEURButton = new javax.swing.JButton();
        JualGBPButton = new javax.swing.JButton();
        BeliGBPButton = new javax.swing.JButton();
        inputUSD = new javax.swing.JTextField();
        inputEUR = new javax.swing.JTextField();
        inputGBP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        WelcomeText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 215, 0));
        WelcomeText.setText("Welcome to the Money Exchange");

        nilaiTukarUSD.setBackground(new java.awt.Color(153, 153, 153));
        nilaiTukarUSD.setForeground(new java.awt.Color(192, 192, 192));

        nilaiTukarEUR.setBackground(new java.awt.Color(153, 153, 153));
        nilaiTukarEUR.setForeground(new java.awt.Color(192, 192, 192));

        nilaiTukarGBP.setBackground(new java.awt.Color(153, 153, 153));
        nilaiTukarGBP.setForeground(new java.awt.Color(192, 192, 192));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Deposit");

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("IDR");

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("USD");

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("EUR");

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("GBP");

        IDRAkunText.setBackground(new java.awt.Color(102, 102, 102));
        IDRAkunText.setForeground(new java.awt.Color(255, 215, 0));
        IDRAkunText.setText("jLabel3");

        USDAkunText.setBackground(new java.awt.Color(102, 102, 102));
        USDAkunText.setForeground(new java.awt.Color(255, 215, 0));
        USDAkunText.setText("jLabel7");

        EURAkunText.setBackground(new java.awt.Color(102, 102, 102));
        EURAkunText.setForeground(new java.awt.Color(255, 215, 0));
        EURAkunText.setText("jLabel8");

        GBPAkunText.setBackground(new java.awt.Color(102, 102, 102));
        GBPAkunText.setForeground(new java.awt.Color(255, 215, 0));
        GBPAkunText.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(IDRAkunText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GBPAkunText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(USDAkunText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EURAkunText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDRAkunText))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(USDAkunText))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EURAkunText))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(GBPAkunText))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        JualUSDButton.setBackground(new java.awt.Color(0, 204, 0));
        JualUSDButton.setForeground(new java.awt.Color(255, 255, 255));
        JualUSDButton.setText("Jual");
        JualUSDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JualUSDButtonActionPerformed(evt);
            }
        });

        BeliUSDButton.setBackground(new java.awt.Color(255, 51, 51));
        BeliUSDButton.setForeground(new java.awt.Color(255, 255, 255));
        BeliUSDButton.setText("Beli");
        BeliUSDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliUSDButtonActionPerformed(evt);
            }
        });

        JualEURButton.setBackground(new java.awt.Color(0, 204, 0));
        JualEURButton.setForeground(new java.awt.Color(255, 255, 255));
        JualEURButton.setText("Jual");
        JualEURButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JualEURButtonActionPerformed(evt);
            }
        });

        BeliEURButton.setBackground(new java.awt.Color(255, 51, 51));
        BeliEURButton.setForeground(new java.awt.Color(255, 255, 255));
        BeliEURButton.setText("Beli");
        BeliEURButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliEURButtonActionPerformed(evt);
            }
        });

        JualGBPButton.setBackground(new java.awt.Color(0, 204, 0));
        JualGBPButton.setForeground(new java.awt.Color(255, 255, 255));
        JualGBPButton.setText("Jual");
        JualGBPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JualGBPButtonActionPerformed(evt);
            }
        });

        BeliGBPButton.setBackground(new java.awt.Color(255, 51, 51));
        BeliGBPButton.setForeground(new java.awt.Color(255, 255, 255));
        BeliGBPButton.setText("Beli");
        BeliGBPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliGBPButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 215, 0));
        jLabel3.setText("Masukkan nominal USD");

        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("Masukkan nominal EUR");

        jLabel8.setForeground(new java.awt.Color(255, 215, 0));
        jLabel8.setText("Masukkan nominal GBP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(WelcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JualUSDButton)
                                .addGap(18, 18, 18)
                                .addComponent(BeliUSDButton)
                                .addGap(18, 18, 18)
                                .addComponent(inputUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(JualEURButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(BeliEURButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputEUR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(JualGBPButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(BeliGBPButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nilaiTukarUSD, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                .addComponent(nilaiTukarEUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nilaiTukarGBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(WelcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nilaiTukarUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JualUSDButton)
                            .addComponent(BeliUSDButton)
                            .addComponent(inputUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addComponent(nilaiTukarEUR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JualEURButton)
                            .addComponent(BeliEURButton)
                            .addComponent(inputEUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nilaiTukarGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JualGBPButton)
                            .addComponent(BeliGBPButton)
                            .addComponent(inputGBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        resetDataDeposit();
        Timer timer = new Timer();
        Random randomizer = new Random();
        
           timer.schedule(new TimerTask() {
                
                public void run() {
                    int i = 0;
                    while (ulangKalkulasi == true) {
                        perubahanNilai = randomizer.nextInt(500)+1;
                        kalkulasiPositif = randomizer.nextBoolean();
                        
                        if(kalkulasiPositif == true) {
                            nilaiTukar[0] = nilaiTukar[0] + perubahanNilai;
                        } else {
                            nilaiTukar[0] = nilaiTukar[0] - perubahanNilai;
                        }
                        
                        perubahanNilai = randomizer.nextInt(500)+1;
                        kalkulasiPositif = randomizer.nextBoolean();
                        
                        if(kalkulasiPositif == true) {
                            nilaiTukar[1] = nilaiTukar[1] + perubahanNilai;
                        } else {
                            nilaiTukar[1] = nilaiTukar[1] - perubahanNilai;
                        }
                        
                        perubahanNilai = randomizer.nextInt(500)+1;
                        kalkulasiPositif = randomizer.nextBoolean();
                        
                        if(kalkulasiPositif == true) {
                            nilaiTukar[2] = nilaiTukar[2] + perubahanNilai;
                        } else {
                            nilaiTukar[2] = nilaiTukar[2] - perubahanNilai;
                        }
                        
                        nilaiTukarUSD.setText("Harga USD : " + String.valueOf(nilaiTukar[0]));
                        nilaiTukarEUR.setText("Harga Euro : " + String.valueOf(nilaiTukar[1]));
                        nilaiTukarGBP.setText("Harga Poundsterling : " + String.valueOf(nilaiTukar[2]));
                        try {
                            Thread.sleep(10000);
                        } catch (InterruptedException e) {
                            
                        }
                    }
                }
            }, 0);
    }//GEN-LAST:event_formWindowOpened

    private void JualGBPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JualGBPButtonActionPerformed
        if(inputGBP.getText().equals("") || inputUSD.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Anda belum memasukkan nominal", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
        inputNominal = Integer.parseInt(inputGBP.getText());
        userGBP = userGBP - inputNominal;
        userIDR = userIDR + (inputNominal * nilaiTukar[2]);
        resetDataDeposit();
        inputGBP.setText("");
        }
    }//GEN-LAST:event_JualGBPButtonActionPerformed

    private void JualUSDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JualUSDButtonActionPerformed
        if(inputUSD.getText().equals("") || inputUSD.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Anda belum memasukkan nominal", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
        inputNominal = Integer.parseInt(inputUSD.getText());
        userUSD = userUSD - inputNominal;
        userIDR = userIDR + (inputNominal * nilaiTukar[0]);
        resetDataDeposit();
        inputUSD.setText("");
        }
    }//GEN-LAST:event_JualUSDButtonActionPerformed

    private void BeliUSDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliUSDButtonActionPerformed
        if(inputUSD.getText().equals("") || inputUSD.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Anda belum memasukkan nominal", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
        inputNominal = Integer.parseInt(inputUSD.getText());
        userUSD = userUSD + inputNominal;
        userIDR = userIDR - (inputNominal * nilaiTukar[0]);
        resetDataDeposit();
        inputUSD.setText("");
        }
    }//GEN-LAST:event_BeliUSDButtonActionPerformed

    private void JualEURButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JualEURButtonActionPerformed
        if(inputEUR.getText().equals("") || inputUSD.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Anda belum memasukkan nominal", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
        inputNominal = Integer.parseInt(inputEUR.getText());
        userEUR = userEUR - inputNominal;
        userIDR = userIDR + (inputNominal * nilaiTukar[1]);
        resetDataDeposit();
        inputEUR.setText("");
        }
    }//GEN-LAST:event_JualEURButtonActionPerformed

    private void BeliEURButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliEURButtonActionPerformed
        if(inputEUR.getText().equals("") || inputUSD.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Anda belum memasukkan nominal", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
        inputNominal = Integer.parseInt(inputEUR.getText());
        userEUR = userEUR + inputNominal;
        userIDR = userIDR - (inputNominal * nilaiTukar[1]);
        resetDataDeposit();
        inputEUR.setText("");
        }
    }//GEN-LAST:event_BeliEURButtonActionPerformed

    private void BeliGBPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliGBPButtonActionPerformed
        if(inputGBP.getText().equals("") || inputUSD.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Anda belum memasukkan nominal", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
        inputNominal = Integer.parseInt(inputGBP.getText());
        userGBP = userGBP + inputNominal;
        userIDR = userIDR - (inputNominal * nilaiTukar[2]);
        resetDataDeposit();
        inputGBP.setText("");
        }
    }//GEN-LAST:event_BeliGBPButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeliEURButton;
    private javax.swing.JButton BeliGBPButton;
    private javax.swing.JButton BeliUSDButton;
    private javax.swing.JLabel EURAkunText;
    private javax.swing.JLabel GBPAkunText;
    private javax.swing.JLabel IDRAkunText;
    private javax.swing.JButton JualEURButton;
    private javax.swing.JButton JualGBPButton;
    private javax.swing.JButton JualUSDButton;
    private javax.swing.JLabel USDAkunText;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JTextField inputEUR;
    private javax.swing.JTextField inputGBP;
    private javax.swing.JTextField inputUSD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nilaiTukarEUR;
    private javax.swing.JLabel nilaiTukarGBP;
    private javax.swing.JLabel nilaiTukarUSD;
    // End of variables declaration//GEN-END:variables
}
